# Generated by Django 5.1.2 on 2024-10-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(choices=[('CONTA_FIXA', 'Conta Fixa'), ('COMPRA', 'Compra'), ('INVESTIMENTO', 'Investimento'), ('LAZER', 'Lazer')], max_length=15)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
            ],
        ),
    ]
